backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "socials"
    label: "Соцсети"
    folder: "src/content/socials"
    create: true
    slug: "{{title}}"
    extention: "json"
    format: "json"
    fields:
      - label: "Название"
        name: "title"
        widget: "string"

      - label: "Ссылка"
        name: "link"
        widget: "string"

  - name: "games-rus"
    label: "Игры (Рус)"
    folder: "src/content/games/ru"
    create: true
    slug: "{{title}}"
    extention: "json"
    format: "json"
    fields:
      - label: "Название"
        hint: "(до 30 символов)"
        name: "title"
        widget: "string"

      - label: "Краткое описание"
        hint: "(до 300 символов)"
        name: "description"
        widget: "markdown"

      - label: "Подробное описание"
        hint: "(до 4000 символов)"
        name: "body"
        widget: "markdown"

      - label: "Жанр"
        name: "genre"
        widget: "select"
        options:
          - { label: "Аркада", value: "arcade" }
          - { label: "RPG", value: "rpg" }
          - { label: "Шутер", value: "shooter" }
          - { label: "Гонки", value: "racing" }
          - { label: "Экшен", value: "action" }
          - { label: "Стратегия", value: "strategy" }
          - { label: "Файтинг", value: "fighting" }
          - { label: "Хоррор", value: "horror" }
          - { label: "Симулятор", value: "simulator" }
          - { label: "Стелс", value: "stealth" }

      - label: "Разработчик"
        name: "developer"
        widget: "string"

      - label: "Издатель"
        name: "publisher"
        widget: "string"

      - label: "Дата выхода"
        name: "date"
        widget: "datetime"
        date_format: "DD.MM.YYYY"
        format: "L"

      - label: "Языки"
        name: "langs"
        widget: "object"
        summary: "{{fields.name}}"
        collapsed: true
        fields:
          - label: "Русский"
            name: "ru"
            widget: "object"
            fields:
              - {
                  label: "Озвучка",
                  name: "voice",
                  widget: "boolean",
                  default: false,
                }
              - {
                  label: "Текст",
                  name: "text",
                  widget: "boolean",
                  default: false,
                }
          - label: "Английский"
            name: "en"
            widget: "object"
            fields:
              - {
                  label: "Озвучка",
                  name: "voice",
                  widget: "boolean",
                  default: false,
                }
              - {
                  label: "Текст",
                  name: "text",
                  widget: "boolean",
                  default: false,
                }

      - label: "Площадки"
        name: "platforms"
        widget: "object"
        fields:
          - {
              label: "App Store",
              name: "apple",
              widget: "string",
              required: false,
            }
          - {
              label: "Google Play",
              name: "google",
              widget: "string",
              required: false,
            }
          - {
              label: "RuStore",
              name: "ru_store",
              widget: "string",
              required: false,
            }
          - {
              label: "AppGallery",
              name: "app_gallery",
              widget: "string",
              required: false,
            }
          - {
              label: "Яндекс Игры",
              name: "yandex",
              widget: "string",
              required: false,
            }
          - { label: "VK Play", name: "vk", widget: "string", required: false }
          - { label: "Steam", name: "steam", widget: "string", required: false }
          - {
              label: "Epic Games",
              name: "epic",
              widget: "string",
              required: false,
            }
          - { label: "Xbox", name: "xbox", widget: "string", required: false }
          - {
              label: "Sony PlayStation",
              name: "playstation",
              widget: "string",
              required: false,
            }
          - {
              label: "Nintendo Switch",
              name: "nintendo",
              widget: "string",
              required: false,
            }

      - label: "Статус"
        name: "status"
        widget: "select"
        default: { label: "Нет", value: "" }
        options:
          - { label: "Нет", value: "" }
          - { label: "В разработке", value: "dev" }
          - { label: "Новинка", value: "new" }
          - { label: "Популярные", value: "hot" }
          - { label: "В тесте", value: "test" }

      - label: "В избранном"
        name: "favorites"
        widget: "select"
        default: { label: "Нет", value: "" }
        options:
          - { label: "Нет", value: "" }
          - { label: "Топ", value: "top" }
          - { label: "Лучшие", value: "best" }

      - label: "Картинка для описания"
        hint: "(Размер 1024 х 500) - строгие требования"
        name: "thumbnail"
        widget: "image"

      - label: "Шапка для секции"
        hint: "(1920 х 760) - строгие требования"
        name: "hero_image"
        widget: "image"

      - label: "Рекламный баннер"
        hint: "(16:9 Лучше 1920х1080) - строгие требования"
        name: "ad_banner"
        widget: "object"
        fields:
          - { label: Источник, name: src, widget: image }
          - { label: Описание, name: alt, widget: string }

      - label: "Галлерея"
        hint: "(от 4 до 10, Размер 16:9 или 9:16, длина каждой стороны – от 320 до 3840) - строгие требования"
        name: "gallery"
        widget: "list"
        summary: "{{fields.alt}}"
        label_singular: "Добавить картинку"
        fields:
          - { label: Источник, name: src, widget: image }
          - { label: Описание, name: alt, widget: string }

  - name: "publishing-rus"
    label: "Издательство (Рус)"
    folder: "src/content/publishing/ru"
    extention: "md"
    format: "frontmatter"
    create: true
    slug: "{{title}}"
    fields:
      - label: "Заголовок"
        name: "title"
        widget: "string"

      - label: "Описание"
        name: "description"
        widget: "string"

      - label: "Обложка"
        name: "thumbnail"
        allow_multiple: false
        widget: "image"

      - label: "Ссылка на раздел"
        name: "link"
        widget: "string"

      - label: "Порядок в секции"
        name: "order"
        widget: "number"
        value_type: "int"

      - label: "Подробное описание"
        name: "body"
        widget: "markdown"

  - name: "services-rus"
    label: "Услуги (Рус)"
    folder: "src/content/services/ru"
    extention: "md"
    format: "frontmatter"
    create: true
    slug: "{{title}}"
    fields:
      - label: "Заголовок"
        name: "title"
        widget: "string"

      - label: "Краткое описание"
        name: "description"
        widget: "markdown"

      - label: "Подробное описание"
        name: "body"
        widget: "markdown"

      - label: "Галлерея"
        name: "gallery"
        widget: "list"
        summary: "{{fields.alt}}"
        label_singular: "Добавить картинку"
        fields:
          - { label: Источник, name: src, widget: image }
          - { label: Описание, name: alt, widget: string }

      - label: "Порядок в секции"
        name: "order"
        widget: "number"
        value_type: "int"
