backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "games-rus"
    label: "Игры (Рус)"
    folder: "src/content/games/ru"
    create: true
    slug: "{{title}}"
    extention: "json"
    format: "json"
    fields:
      - label: "Заголовок"
        name: "title"
        widget: "string"

      - label: "Обложка"
        name: "thumbnail"
        allow_multiple: false
        widget: "image"

      - label: "Теги"
        name: "tags"
        widget: "list"

      - label: "Ссылки на платформы"
        name: "links"
        widget: "object"
        fields:
          - { label: "Google", name: "google", widget: "string" }
          - { label: "Apple", name: "apple", widget: "string" }

      - label: "Ссылка на раздел"
        name: "link"
        widget: "string"

      - label: "Категория"
        name: "category"
        widget: "select"
        default: { label: "Нет", value: "" }
        options:
          - { label: "Нет", value: "" }
          - { label: "В разработке", value: "dev" }
          - { label: "Новинка", value: "new" }
          - { label: "Популярные", value: "hot" }
          - { label: "В тесте", value: "test" }

  - name: "publishing-rus"
    label: "Издательство (Рус)"
    folder: "src/content/publishing/ru"
    extention: "md"
    format: "frontmatter"
    create: true
    slug: "{{title}}"
    fields:
      - label: "Заголовок"
        name: "title"
        widget: "string"

      - label: "Описание"
        name: "description"
        widget: "string"

      - label: "Обложка"
        name: "thumbnail"
        allow_multiple: false
        widget: "image"

      - label: "Ссылка на раздел"
        name: "link"
        widget: "string"

      - label: "Порядок в секции"
        name: "order"
        widget: "number"
        value_type: "int"

      - label: "Подробное описание"
        name: "body"
        widget: "markdown"

  - name: "services-rus"
    label: "Услуги (Рус)"
    folder: "src/content/services/ru"
    extention: "md"
    format: "frontmatter"
    create: true
    slug: "{{title}}"
    fields:
      - label: "Заголовок"
        name: "title"
        widget: "string"

      - label: "Ссылка на раздел"
        name: "link"
        widget: "string"

      - label: "Галлерея"
        name: "images"
        widget: "list"
        fields:
          - { label: Ссылка, name: src, widget: image }
          - { label: Описание, name: alt, widget: string }

      - label: "Порядок в секции"
        name: "order"
        widget: "number"
        value_type: "int"

      - label: "Подробное описание"
        name: "body"
        widget: "markdown"
