backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "socials"
    label: "Соцсети"
    folder: "src/content/socials"
    create: true
    slug: "{{title}}"
    extention: "json"
    format: "json"
    fields:
      - label: "Название"
        name: "title"
        widget: "string"

      - label: "Ссылка"
        name: "link"
        widget: "string"

  - name: "games-rus"
    label: "Игры (Рус)"
    folder: "src/content/games/ru"
    media_folder: "/public/images/games/{{fields.title}}"
    create: true
    slug: "{{title}}"
    extention: "json"
    format: "json"
    fields:
      - label: "Название"
        hint: "(до 30 символов)"
        name: "title"
        widget: "string"

      - label: "Краткое описание"
        hint: "(до 300 символов)"
        name: "description"
        widget: "markdown"
        default: >-
          ## Заголовок

          Банальные, но неопровержимые выводы, а также независимые государства призывают нас к новым свершениям, которые, в свою очередь, должны быть преданы социально-демократической анафеме. Противоположная точка зрения подразумевает, что некоторые особенности внутренней политики будут функционально разнесены на независимые элементы.

      - label: "Подробное описание"
        hint: "(до 4000 символов)"
        name: "body"
        widget: "markdown"
        default: >
          ## Заголовок

          Каждый из нас понимает очевидную вещь: реализация намеченных плановых заданий способствует повышению качества поставленных обществом задач. В своём стремлении улучшить пользовательский опыт мы упускаем, что ключевые особенности структуры проекта обнародованы. Таким образом, постоянный количественный рост и сфера нашей активности предопределяет высокую востребованность позиций, занимаемых участниками в отношении поставленных задач. Не следует, однако, забывать, что начало повседневной работы по формированию позиции создаёт предпосылки для форм воздействия. Картельные сговоры не допускают ситуации, при которой представители современных социальных резервов, превозмогая сложившуюся непростую экономическую ситуацию, объявлены нарушающими общечеловеческие нормы этики и морали. Идейные соображения высшего порядка, а также постоянное информационно-пропагандистское обеспечение нашей деятельности играет важную роль в формировании анализа существующих паттернов поведения.

          ### Подзаголовок

          Банальные, но неопровержимые выводы, а также независимые государства призывают нас к новым свершениям, которые, в свою очередь, должны быть преданы социально-демократической анафеме. Противоположная точка зрения подразумевает, что некоторые особенности внутренней политики будут функционально разнесены на независимые элементы.

          Являясь всего лишь частью общей картины, активно развивающиеся страны третьего мира призывают нас к новым свершениям, которые, в свою очередь, должны быть функционально разнесены на независимые элементы. Для современного мира современная методология разработки, а также свежий взгляд на привычные вещи — безусловно открывает новые горизонты для приоретизации разума над эмоциями! Для современного мира реализация намеченных плановых заданий позволяет выполнить важные задания по разработке инновационных методов управления процессами. В своём стремлении повысить качество жизни, они забывают, что курс на социально-ориентированный национальный проект способствует подготовке и реализации переосмысления внешнеэкономических политик.

      - label: "Жанр"
        name: "genre"
        widget: "select"
        options:
          - { label: "Аркада", value: "arcade" }
          - { label: "RPG", value: "rpg" }
          - { label: "Шутер", value: "shooter" }
          - { label: "Гонки", value: "racing" }
          - { label: "Экшен", value: "action" }
          - { label: "Стратегия", value: "strategy" }
          - { label: "Файтинг", value: "fighting" }
          - { label: "Хоррор", value: "horror" }
          - { label: "Симулятор", value: "simulator" }
          - { label: "Стелс", value: "stealth" }

      - label: "Разработчик"
        name: "developer"
        widget: "string"

      - label: "Издатель"
        name: "publisher"
        widget: "string"

      - label: "Дата выхода"
        name: "date"
        widget: "datetime"
        date_format: "DD.MM.YYYY"
        format: "L"

      - label: "Языки"
        name: "langs"
        widget: "list"
        summary: "{{fields.lang}}"
        collapsed: true
        default:
          - { lang: "Русский", slug: ru, voice: false, text: false }
          - { lang: "Английский", slug: en, voice: false, text: false }
        fields:
          - { label: "Язык", name: "lang", widget: "string" }
          - { label: "ID", name: "slug", widget: "string" }
          - {
              label: "Озвучка",
              name: "voice",
              widget: "boolean",
              default: false,
            }
          - { label: "Текст", name: "text", widget: "boolean", default: false }

      - label: "Площадки"
        name: "platforms"
        widget: "list"
        summary: "{{fields.title}}"
        default:
          - {
              title: "Sony Playstation",
              slug: playstation,
              svg_href: "",
              href: "",
            }
          - { title: "RuStore", slug: ru_store, svg_href: "", href: "" }
          - { title: "Steam", slug: steam, svg_href: "", href: "" }
          - { title: "Yandex", slug: yandex, svg_href: "", href: "" }
          - { title: "X-Box", slug: xbox, svg_href: "", href: "" }
          - {
              title: "App Gallery (Huawei)",
              slug: app_gallery,
              svg_href: "",
              href: "",
            }
          - { title: "VK", slug: vk, svg_href: "", href: "" }
          - { title: "Nintendo", slug: nintendo, svg_href: "", href: "" }
          - { title: "Play Market", slug: google, svg_href: "", href: "" }
          - { title: "App Store", slug: apple, svg_href: "", href: "" }
        fields:
          - { label: "Name", name: "title", widget: "string" }
          - { label: "ID", name: "slug", widget: "string" }
          - { label: "Ссылка", name: "href", widget: "string" }
          - {
              label: "Ссылка на SVG",
              name: "svg_href",
              widget: "string",
              default: "",
              required: false,
            }

      - label: "Статус"
        name: "status"
        widget: "select"
        required: false
        default: null
        options:
          - { label: "В разработке", value: "dev" }
          - { label: "Новинка", value: "new" }
          - { label: "Популярные", value: "hot" }
          - { label: "В тесте", value: "test" }

      - label: "В избранном"
        name: "favorites"
        widget: "select"
        required: false
        default: null
        options:
          - { label: "Топ", value: "top" }
          - { label: "Лучшие", value: "best" }

      - label: "Картинка для описания"
        hint: "(Размер 1024 х 500) - строгие требования"
        name: "thumbnail"
        widget: "image"

      - label: "Шапка для секции"
        hint: "(1920 х 760) - строгие требования"
        name: "hero_image"
        widget: "image"

      - label: "Рекламный баннер"
        hint: "(16:9 Лучше 1920х1080) - строгие требования"
        name: "ad_banner"
        widget: "object"
        fields:
          - { label: Источник, name: src, widget: image }
          - { label: Описание, name: alt, widget: string }

      - label: "Галлерея"
        hint: "(от 4 до 10, Размер 16:9 или 9:16, длина каждой стороны – от 320 до 3840) - строгие требования"
        name: "gallery"
        widget: "list"
        summary: "{{fields.alt}}"
        label_singular: "Добавить картинку"
        fields:
          - { label: Источник, name: src, widget: image }
          - { label: Описание, name: alt, widget: string }

  - name: "publishing-rus"
    label: "Издательство (Рус)"
    folder: "src/content/publishing/ru"
    extention: "md"
    format: "frontmatter"
    create: true
    slug: "{{title}}"
    fields:
      - label: "Заголовок"
        name: "title"
        widget: "string"

      - label: "Описание"
        name: "description"
        widget: "string"

      - label: "Обложка"
        name: "thumbnail"
        allow_multiple: false
        widget: "image"

      - label: "Ссылка на раздел"
        name: "link"
        widget: "string"

      - label: "Порядок в секции"
        name: "order"
        widget: "number"
        value_type: "int"

      - label: "Подробное описание"
        name: "body"
        widget: "markdown"

  - name: "services-rus"
    label: "Услуги (Рус)"
    folder: "src/content/services/ru"
    extention: "md"
    format: "frontmatter"
    create: true
    slug: "{{title}}"
    fields:
      - label: "Заголовок"
        name: "title"
        widget: "string"

      - label: "Краткое описание"
        name: "description"
        widget: "markdown"

      - label: "Подробное описание"
        name: "body"
        widget: "markdown"

      - label: "Галлерея"
        name: "gallery"
        widget: "list"
        summary: "{{fields.alt}}"
        label_singular: "Добавить картинку"
        fields:
          - { label: Источник, name: src, widget: image }
          - { label: Описание, name: alt, widget: string }

      - label: "Порядок в секции"
        name: "order"
        widget: "number"
        value_type: "int"
