backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "games"
    label: "Games"
    folder: "src/content/games/ru"
    create: true
    slug: "{{slug}}"
    extention: "json"
    format: "json"
    fields:
      - { label: "Name", name: "name", widget: "string" }

      - label: "Image"
        name: "image"
        widget: "object"
        fields:
          - { label: "Source", name: "src", widget: "image" }
          - { label: "Alt-text", name: "alt", widget: "string" }

      - { label: "Tags", name: tags, widget: "list" }

      - label: "Links"
        name: "links"
        widget: "object"
        fields:
          - { label: "Google", name: "google", widget: "string" }
          - { label: "Apple", name: "apple", widget: "string" }

      - label: "Category"
        name: "category"
        widget: "select"
        options:
          - { label: "Dev", value: "dev" }
          - { label: "New", value: "new" }
          - { label: "Hot", value: "hot" }
          - { label: "Test", value: "test" }
