backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "games" # Used in routes, e.g., /admin/collections/blog
    label: "Games" # Used in the UI
    folder: "src/content/games/ru" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{name}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Name", name: "name", widget: "string" }

      - label: "Image"
        name: "image"
        widget: "object"
        fields:
          - { label: "Source", name: "src", widget: "image" }
          - { label: "Alt-text", name: "alt", widget: "string" }

      - { label: "Tags", name: tags, widget: "list" }

      - label: "Links"
        name: "links"
        widget: "object"
        fields:
          - { label: "Google", name: "google", widget: "string" }
          - { label: "Apple", name: "apple", widget: "string" }

      - label: "Category"
        name: "category"
        widget: "select"
        options:
          - { label: "Dev", value: "dev" }
          - { label: "New", value: "new" }
          - { label: "Hot", value: "hot" }
          - { label: "Test", value: "test" }
